[package]
name = "guessing_game"
version = "0.1.0"
edition = "2018"
authors = ["Jonathan V. <hxn.dev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"